### ISSUE TITLE
CDI SA is not getting permissions in install script

### ISSUE THREAD

**Issue by awels** [xsgordon/kubevirt-minishift-demo#2]
You need to add something like:

${OC} adm policy add-scc-to-user privileged system:serviceaccount:kube-system:cdi-sa

to demo.sh in order to give CDI the needed permissions to access hostPath based storage.

**Comment by xsgordon** [comment]
@awels I assume this is in relation to https://github.com/kubevirt/containerized-data-importer/issues/452 ?

I tried that line and it didn't seem to help, for this one if I'm using the un-modified CDI manifest should i be using default instead of kube-system as the namespace? I'll try this shortly either way...

**Comment by awels** [comment]
No that line is for when you get to try cloning, in order to run the cloner pod you need those permissions.

**Comment by xsgordon** [comment]
OK gotcha. I'm still encountering the other issue creating the initial PVC-backed VM.
